//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public Customer()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public int customerId { get; set; }
        public string customerName { get; set; }
        public string gender { get; set; }
        public string dob { get; set; }
        public string address { get; set; }
        public string state { get; set; }
        public string city { get; set; }
        public string pincode { get; set; }
        public string phoneNo { get; set; }
        public string email { get; set; }
        public string createdDate { get; set; }
        public string editedDate { get; set; }
        public string userId { get; set; }
        public string branchId { get; set; }
        public Nullable<int> managerId { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual Branch Branch { get; set; }
        public virtual Manager Manager { get; set; }
    }
}
