//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMedal
    {
        public CustomerMedal()
        {
            this.Accounts = new HashSet<Account>();
        }
    
        public string type { get; set; }
        public Nullable<int> min { get; set; }
        public Nullable<int> max { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
