//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Manager
    {
        public Manager()
        {
            this.Customers = new HashSet<Customer>();
        }
    
        public string managerName { get; set; }
        public string branchId { get; set; }
        public int managerId { get; set; }
        public string address { get; set; }
        public string phoneNo { get; set; }
        public string userId { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual Login Login { get; set; }
    }
}
