//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        public long transactionId { get; set; }
        public long fromAccountNo { get; set; }
        public long toAccountNo { get; set; }
        public string transactionDate { get; set; }
        public int amount { get; set; }
        public string transactionType { get; set; }
        public string comments { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Account Account1 { get; set; }
    }
}
